AWSTemplateFormatVersion: 2010-09-09
Resources:
  MySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: MySecret
      Description: "This secret has a dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: "password"
        PasswordLength: 10
        ExcludePunctuation: "true"

      Tags:
        -
          Key: Name
          Value: First-Secret
  




